name: Build and Run Docker Container with Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build Docker image
        run: |
            ls -ltr
            docker build -t my-nginx-image .

      - name: Push Docker image to ECR
         run:|
          IMAGE_TAG=latest
          REPOSITORY_URI=${{ secrets.ECR_REPOSITORY_URI }}
          docker push $REPOSITORY_URI:$IMAGE_TAG

